<?php
// $Id: xoops_version.php,v 1.9 2004/09/27 16:57:22 phppp Exp $
//  ------------------------------------------------------------------------ //
//                        XMLINE for XOOPS                                   //
//             Copyright (c) 2004 Xoops China Community                      //
//                    <http://www.xoops.org.cn/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
// Author: D.J.(phppp) php_pp@hotmail.com                                    //
// URL: http://xoops.org.cn                                              //
// ------------------------------------------------------------------------- //
include_once(XOOPS_ROOT_PATH.'/modules/xmline/include/vars.php');

$modversion['name'] = _MI_XMLINE_NAME;
$modversion['version'] = 2.0;
$modversion['description'] = _MI_XMLINE_DESC;
$modversion['credits'] = "Kellan Elliott-McCrea <kellan@protest.net>; imhsy (http://xoops.hsyong.com)";
$modversion['author'] = "phppp (D.J.) ( http://xoops.org.cn/ )";
$modversion['help'] = "http://xoops.org.cn";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/xmline.gif";
$modversion['dirname'] = "xmline";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
$modversion['tables'][0] = "xmline_digests";
$modversion['tables'][1] = "xmline_categories";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

$modversion['onInstall'] = 'include/functions.php';

// Templates
$modversion['templates'][1]['file'] = 'xmline_index.html';
$modversion['templates'][1]['description'] = '';
//$modversion['templates'][2]['file'] = 'xmline_custom.html';
//$modversion['templates'][2]['description'] = '';
$modversion['templates'][2]['file'] = 'xmline_feed.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'xmline_item.html';
$modversion['templates'][3]['description'] = '';

// Blocks
$modversion['blocks'][1]['file'] = "xmline_blocks.php";
$modversion['blocks'][1]['name'] = _MI_XMLINE_BLOCK_LIST;
$modversion['blocks'][1]['description'] = _MI_XMLINE_BLOCK_LIST_DESC;
$modversion['blocks'][1]['show_func'] = "b_xmline_show";
$modversion['blocks'][1]['options'] = "list|2|60|30|2"; // block type|items from each digest|total items|item title length|columns
$modversion['blocks'][1]['edit_func'] = "b_xmline_edit";
$modversion['blocks'][1]['template'] = 'xmline_block_list.html';

$modversion['blocks'][2]['file'] = "xmline_blocks.php";
$modversion['blocks'][2]['name'] = _MI_XMLINE_BLOCK_SCROLL;
$modversion['blocks'][2]['description'] = _MI_XMLINE_BLOCK_SCROLL_DESC;
$modversion['blocks'][2]['show_func'] = "b_xmline_show";
$modversion['blocks'][2]['options'] = "scroll|2|60|30|200|10";  // block type|items from each xmline|total items|item title length|scroll delay|scroll amount
$modversion['blocks'][2]['edit_func'] = "b_xmline_edit";
$modversion['blocks'][2]['template'] = 'xmline_block_scroll.html';

$modversion['blocks'][3]['file'] = "xmline_blocks.php";
$modversion['blocks'][3]['name'] = _MI_XMLINE_BLOCK_SPOTLIGHT;
$modversion['blocks'][3]['description'] = _MI_XMLINE_BLOCK_SPOTLIGHT_DESC;
$modversion['blocks'][3]['show_func'] = "b_xmline_spotlight_show";
$modversion['blocks'][3]['options'] = "1|5|100";  // digest_id|Items|description length (0 for no limit)
$modversion['blocks'][3]['edit_func'] = "b_xmline_spotlight_edit";
$modversion['blocks'][3]['template'] = 'xmline_block_spotlight.html';

// Menu
$modversion['hasMain'] = 1;

// Config Settings (only for modules that need config settings generated automatically)
$modversion['config'][0]['name'] = 'title_length';
$modversion['config'][0]['title'] = '_MI_XMLINE_TITLELENGTH';
$modversion['config'][0]['description'] = '_MI_XMLINE_TITLELENGTH_DESC';
$modversion['config'][0]['formtype'] = 'textbox';
$modversion['config'][0]['valuetype'] = 'int';
$modversion['config'][0]['default'] = 30;

$modversion['config'][1]['name'] = 'two_column';
$modversion['config'][1]['title'] = '_MI_XMLINE_TWOCOLUMN';
$modversion['config'][1]['description'] = '_MI_XMLINE_TWOCOLUMN_DESC';
$modversion['config'][1]['formtype'] = 'yesno';
$modversion['config'][1]['valuetype'] = 'int';
$modversion['config'][1]['default'] = 1;

$modversion['config'][2]['name'] = 'allow_submit';
$modversion['config'][2]['title'] = '_MI_XMLINE_ALLOWSUBMIT';
$modversion['config'][2]['description'] = '_MI_XMLINE_ALLOWSUBMIT_DESC';
$modversion['config'][2]['formtype'] = 'yesno';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = 1;

$modversion['config'][3]['name'] = 'auto_approve';
$modversion['config'][3]['title'] = '_MI_XMLINE_AUTOAPPROVE';
$modversion['config'][3]['description'] = '_MI_XMLINE_AUTOAPPROVE_DESC';
$modversion['config'][3]['formtype'] = 'yesno';
$modversion['config'][3]['valuetype'] = 'int';
$modversion['config'][3]['default'] = 0;

$modversion['config'][4]['name'] = 'allow_upload';
$modversion['config'][4]['title'] = '_MI_XMLINE_ALLOWUPLOAD';
$modversion['config'][4]['description'] = '_MI_XMLINE_ALLOWUPLOAD_DESC';
$modversion['config'][4]['formtype'] = 'yesno';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = 0;

$modversion['config'][10]['name'] = 'allowed_extension';
$modversion['config'][10]['title'] = '_MI_XMLINE_ALLOWEXTENSION';
$modversion['config'][10]['description'] = '_MI_XMLINE_ALLOWEXTENSION_DESC';
$modversion['config'][10]['formtype'] = 'textbox';
$modversion['config'][10]['valuetype'] = 'text';
$modversion['config'][10]['default'] = 'jpg|jpeg|gif|png';

$modversion['config'][5]['name'] = 'image_path';
$modversion['config'][5]['title'] = '_MI_XMLINE_IMAGEPATH';
$modversion['config'][5]['description'] = '_MI_XMLINE_IMAGEPATH_DESC';
$modversion['config'][5]['formtype'] = 'textbox';
$modversion['config'][5]['valuetype'] = 'text';
$modversion['config'][5]['default'] = 'uploads/xmline';

$modversion['config'][6]['name'] = 'allow_custom';
$modversion['config'][6]['title'] = '_MI_XMLINE_ALLOWCUSTOM';
$modversion['config'][6]['description'] = '_MI_XMLINE_ALLOWCUSTOM_DESC';
$modversion['config'][6]['formtype'] = 'yesno';
$modversion['config'][6]['valuetype'] = 'int';
$modversion['config'][6]['default'] = 1;

$modversion['config'][7]['name'] = 'header';
$modversion['config'][7]['title'] = '_MI_XMLINE_HEADER';
$modversion['config'][7]['description'] = '_MI_XMLINE_HEADER_DESC';
$modversion['config'][7]['formtype'] = 'textbox';
$modversion['config'][7]['valuetype'] = 'text';
$modversion['config'][7]['default'] = '<h2>XMLine</h2>';

$modversion['config'][8]['name'] = 'footer';
$modversion['config'][8]['title'] = '_MI_XMLINE_FOOTER';
$modversion['config'][8]['description'] = '_MI_XMLINE_FOOTER_DESC';
$modversion['config'][8]['formtype'] = 'textbox';
$modversion['config'][8]['valuetype'] = 'text';
$modversion['config'][8]['default'] = '';


$modversion['releasedate'] = "July 22nd, 2006";
$modversion['status'] = "stable";
$modversion['TODO'] = "";

$modversion['author_website'][1]['url'] = "http://xoops.org.cn";
$modversion['author_website'][1]['name'] = "Xoops China";
$modversion['author_email'] = "php_pp@hotmail.com";
$modversion['demo_site_url'] = "http://xoops.org.cn/modules/xmline";
$modversion['demo_site_name'] = "Xoops China";
$modversion['readme'] = XOOPS_URL."/modules/xmline/readme.".$xoopsConfig['language'].".htm";
$modversion['support_site_url'] = "http://xoops.org.cn";
$modversion['support_site_name'] = "Xoops China";
$modversion['translator']= "";
$modversion['ack'] = "
To Mr Xoops: <br />
-- Kazumi Ono (onokazu) http://jp.xoops.org/ <br />
-- Goghs Cheng (goghs) http://www.eqiao.com/ <br />
";
?>